### ISSUE TITLE
Wallet connect popup not showing in iOS 16.5

### ISSUE THREAD

**Issue by florin-pop** [MetaMask/metamask-ios-sdk#75]
Hello,

I ran the included Example app on iOS 15 and 16.5. On version 16.5 the wallet connect modal view popup is not being shown. The behaviour also seems to be different when trying to connect from a web page (such as opensea.io). In iOS 15 MetaMask opens with the same browser page, while in iOS 16.5 MetaMask does nothing. However when manually navigating to said URL the connect popup is being shown. Both apps have identical settings and were freshly installed today. I also tried 3rd party apps that integrate MetaMask and they seem to be broken as well. Do you have any advice on how to mitigate this?

![IMG_0005](https://github.com/MetaMask/metamask-ios-sdk/assets/13623704/ff7c48dd-8e03-44ef-ae75-23000c039471)
![IMG_0003](https://github.com/MetaMask/metamask-ios-sdk/assets/13623704/08f89450-b0e7-4e7e-bf77-fc0ac0631d3a)
![IMG_0007](https://github.com/MetaMask/metamask-ios-sdk/assets/13623704/850ce17e-bb86-4b1f-878e-f32bfb0ea594)

**Comment by christopherferreira9** [comment]
Hi @florin-pop ! 
Let me provide feedback one by one.
_On version 16.5 the wallet connect modal view popup is not being shown_
What wallet version are you using? This is using 6.3.0 (1095) (it's not using the example but uses the same exact version of the iOS SDK:
https://github.com/MetaMask/metamask-ios-sdk/assets/104831203/797f54c2-358d-42a1-b0f3-d3ec17fecc5a


_The behaviour also seems to be different when trying to connect from a web page (such as opensea.io)_
Opensea does not use the iOS SDK. The iOS SDK is meant to be used by native iOS Apps. OpenSea uses a different protocol and the issue you mentioned has been fixed in a newer version (still not in the AppStore)

_In iOS 15 MetaMask opens with the same browser page, while in iOS 16.5 MetaMask does nothing_
The deeplink in video 3 directs you to the in-app browser and as above, it is not related to the iOS SDK. When deeplinking to the in-app browser the only thing that happens is that the page is open on said in-app browser so you need to manually go into the "Connect Wallet" screen.
MetaMask wallet v6.3.0 (1095) and iOS 16.5:
https://github.com/MetaMask/metamask-ios-sdk/assets/104831203/c191d756-de01-4168-9bdd-beea79223f46

Given this, OpenSea supports WalletConnect and we are integrated with WalletConnect meaning that you can prompt the connect dialog directly from the OpenSea in the device browser via WalletConnect:
https://github.com/MetaMask/metamask-ios-sdk/assets/104831203/e76a80d9-518a-4326-b4bd-6964abcc3b38

Let us know if you have any other questions!

**Comment by florin-pop** [comment]
Hi @christopherferreira9. Thanks for addressing the issue. I'm using the latest version of MetaMask (6.3.0) that is available in the AppStore. I understand that it works for you, however it doesn't work for me so it looks like it's not an obvious problem that is easy to debug so if you need some logs from me just let me know. It also doesn't  work with the OpenSea app which I'm guessing is using WalletConnect:

https://github.com/MetaMask/metamask-ios-sdk/assets/13623704/2059df31-10dc-49c8-bb45-be4c503081e5

**Comment by christopherferreira9** [comment]
Hi @florin-pop ! You're absolutely right, I'm still investigating, I've only closed the issue as it doesn't relate to the MetaMask iOS SDK but rather the [Wallet](https://github.com/MetaMask/metamask-mobile) itself. Using the OpenSea app also works on my device which is an iPhone 11. I'll let you know if I manage to find the root cause. Is that video also from the iPhone 14 Pro?

**Comment by florin-pop** [comment]
Yes it is, I can try to run it on an iPad some time tomorrow and will report back.

**Comment by florin-pop** [comment]
I installed MetaMask and OpenSea on a freshly setup iPad and still can't get MetaMask to show the connect popup. Other wallets like TrustWallet or Rainbow do work. Should I open an issue in the wallet repo?
![a](https://github.com/MetaMask/metamask-ios-sdk/assets/13623704/682ca2dc-eebe-4ed7-b4b0-799373d26c00)

**Comment by christopherferreira9** [comment]
Yes please, thank you @florin-pop
